platform :ios, '8.0'
use_frameworks!

target 'SRWebSocketChat' do
  pod 'AFNetworking', '~> 2.6'
  pod 'SocketRocket', '~> 0.5'
  pod 'YTKKeyValueStore'
  pod 'YYModel'
  pod 'JSQMessagesViewController'
  pod 'ReactiveCocoa', '~> 2.5'
end
